### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by seesemichaelj** [ryanjon2040/Discord-UE4#1]
Perhaps this is just a documentation of putting the `.so` file in a separate `Binaries` directory, but I'm skeptical the current instructions of putting all of the libraries from the SDK into `Binaries/Win64` will work

Looks like there's more documentation about how to support this [here](https://docs.unrealengine.com/en-US/Programming/BuildTools/UnrealBuildTool/ThirdPartyLibraries/index.html)

**Comment by ryanjon2040** [comment]
I hope I'll get help on Linux because I have no Linux machine to test this plugin.
