### ISSUE TITLE
Destroy Discord Object

### ISSUE THREAD

**Issue by kkrypt0nn** [ryanjon2040/Discord-UE4#11]
How can I completely stop the game to show up on Discord when the game shutdowns? I tried to destroy the Discord Object but it still shows the game on Discord.

**Comment by ryanjon2040** [comment]
@kkrypt0nn Hi. I just released a [new version](https://github.com/ryanjon2040/Discord-UE4/releases/latest) (this issue might have been fixed with 39ef3d81a4a79d863e16566842656168c0b92808). Please try it out and let me know.

**Comment by kkrypt0nn** [comment]
I will try it as soon as possible and give you a feedback, thanks :)

**Comment by ryanjon2040** [comment]
You can join discord and let me know. https://discord.gg/S7ykM2q

**Comment by kkrypt0nn** [comment]
Works fine now, thanks a lot!
