### ISSUE TITLE
Shipping Issue [missing discord_game_sdk.dll]

### ISSUE THREAD

**Issue by DiabloFox** [ryanjon2040/Discord-UE4#4]
Hi ! Then I do a build the game wont launch and i'm stuck with this error message, in PIE it work, in standalone mode too but then I build for "Windows (64-bit)" .

![Capture_726](https://user-images.githubusercontent.com/30510918/85908392-2999f100-b815-11ea-9a51-6b073c94d253.PNG)

In english  : 
"Unable to execute the code, because discord_game_sdk.dll is not found. The reinstallation of the program can resolve the probleme"

**Comment by ryanjon2040** [comment]
You need to copy *discord_game_sdk.dll* from the Binaries/Win64 folder to your packaged games exe file. That is right next to YourGameName-Win64-Shipping.exe.

**Comment by DiabloFox** [comment]
Thanks You ! It work ! 
![Capture_727](https://user-images.githubusercontent.com/30510918/85926664-32d09f80-b8a1-11ea-8738-cfed99e11586.PNG)

**Comment by ryanjon2040** [comment]
[For reference] Issue fixed in 15bb4643b8c2e60e9acb49749936c2f78a9da541
